apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "2048-app"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nobleman97/python-practice
    targetRevision: master
    path: kubernetes/

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
